# Generated by Django 5.2.1 on 2026-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('solicitud_problema', models.TextField()),
                ('accion', models.TextField()),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalagoItem',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'catalago_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id_evidencia', models.AutoField(primary_key=True, serialize=False)),
                ('archivo_vinculo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('metadatos', models.JSONField()),
                ('estado_revision', models.CharField(max_length=9)),
            ],
            options={
                'db_table': 'evidencia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.AutoField(primary_key=True, serialize=False)),
                ('avance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cumplimiento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ajuste', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semaforo', models.CharField(max_length=8)),
                ('fecha_calculo', models.DateTimeField()),
            ],
            options={
                'db_table': 'indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id_meta', models.AutoField(primary_key=True, serialize=False)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad', models.CharField(max_length=50)),
                ('ponderador', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'meta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias_computables', models.IntegerField()),
                ('estado', models.IntegerField(blank=True, null=True)),
                ('umbral_regular', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umbral_exelencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('version_parametros', models.IntegerField()),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Validacion',
            fields=[
                ('id_validacion', models.IntegerField(primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=17)),
                ('fecha', models.DateTimeField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(max_length=100)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'validacion',
                'managed': False,
            },
        ),
    ]
