# Generated by Django 5.2.1 on 2026-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delegacion',
            fields=[
                ('id_delegacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('territorio', models.CharField(blank=True, max_length=45, null=True)),
                ('calle', models.CharField(blank=True, max_length=60, null=True)),
                ('numero_calle', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'delegacion',
                'managed': False,
            },
        ),
    ]
