# Generated by Django 5.2.1 on 2026-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compromiso',
            fields=[
                ('id_compromiso', models.AutoField(primary_key=True, serialize=False)),
                ('origen', models.CharField(max_length=100)),
                ('solicitante', models.CharField(max_length=150)),
                ('territorio', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_comprometida', models.DateField()),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('apoyo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'compromiso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObservacionCompromiso',
            fields=[
                ('id_observacioncomp', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'observacion_compromiso',
                'managed': False,
            },
        ),
    ]
