# Generated by Django 5.2.1 on 2026-09-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id_auditoria', models.IntegerField(primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField()),
                ('entidad', models.CharField(max_length=100)),
                ('identificador', models.IntegerField()),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('vigencia', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargoServicio',
            fields=[
                ('pk', models.CompositePrimaryKey('id_servicios', 'id_cargo', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cargo_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalagoServicio',
            fields=[
                ('id_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'catalago_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogoRoles',
            fields=[
                ('id_roles', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'catalogo_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=60)),
                ('apellido_materno', models.CharField(blank=True, max_length=60, null=True)),
                ('estado', models.IntegerField()),
                ('telefono', models.CharField(blank=True, max_length=45, null=True)),
                ('correo', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
    ]
